#!/bin/bash -l
#PBS -A UGIT0046
#PBS -N sweep
#PBS -j oe
#PBS -r n
#PBS -l walltime=12:00:00
#PBS -q casper
#PBS -l select=1:ncpus=1:mem=40GB:ngpus=1:gpu_type=a100
#PBS -M kenzhao@unc.edu
#PBS -m n
#
# sweep_worker.sh — one short PUMP run for the source-sensitivity sweep. Same environment and GPU
# handling as submit_casper.sh, but simname / outdir / stop_days / source flags are all set by TAG so
# the driver (sweep_source.sh) can fan out several configs. Do NOT qsub this directly; use the driver.
#
# Per-config source flags are chosen by TAG below. Everything runs the PUMP case (--tide=0 --pump=1),
# because the near-plume internal tide we are measuring is generated by the modulated discharge.

cd "$PBS_O_WORKDIR" || exit 1
mkdir -p logs output/sweep

module purge
module load ncarenv/23.10
module load peak-memusage
module list

export JULIA_DEPOT_PATH="${JULIA_DEPOT_PATH:-/glade/work/$USER/.julia}"

# --- GPU selection + node health check (identical to submit_casper.sh) --------------------------
echo "host=$(hostname)  PBS CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-<unset>}"
echo "--- nvidia-smi -L ---"; nvidia-smi -L || echo "nvidia-smi: no GPU / driver error on $(hostname)"
nvis=$(nvidia-smi -L 2>/dev/null | grep -c '^GPU')
if [[ "$nvis" -eq 0 ]]; then
    echo "FATAL: no usable GPU on $(hostname) — likely a bad node. Report it and resubmit." >&2
    exit 1
elif [[ "${CUDA_VISIBLE_DEVICES:-}" == GPU-* || "${CUDA_VISIBLE_DEVICES:-}" == MIG-* ]]; then
    if [[ "$nvis" -le 1 ]]; then
        export CUDA_VISIBLE_DEVICES=0
    else
        gpu_idx=$(nvidia-smi --query-gpu=uuid,index --format=csv,noheader \
                  | awk -F', *' -v u="$CUDA_VISIBLE_DEVICES" '$1==u{print $2; exit}')
        export CUDA_VISIBLE_DEVICES="${gpu_idx:-0}"
    fi
fi
echo "using CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES on $(hostname)"
# ------------------------------------------------------------------------------------------------

JULIA="${JULIA:-$HOME/.juliaup/bin/julia}"
SCRIPT="${SCRIPT:-iceplume.jl}"
DAYS="${DAYS:-3}"                 # short run: enough M2 cycles to measure the swing, cheap enough to sweep
TAG="${TAG:-s0_baseline}"

# TAG -> source flags. Walks from the current (diffuse) source to a thin/stiff/narrow/stronger one.
# s0 uses NO source flags (reproduces the current ~0.01 run). s4 needs the --src_gain knob added to
# iceplume.jl (backward-compatible; if you did not sync that edit to Casper, skip s4).
case "$TAG" in
  s0_baseline)  SRC="" ;;
  s1_thin)      SRC="--z_src_bot=-25" ;;
  s2_thinstiff) SRC="--z_src_bot=-25 --sig_src=25" ;;
  s3_narrow)    SRC="--z_src_bot=-25 --sig_src=25 --y_src=90" ;;
  s4_gain)      SRC="--z_src_bot=-25 --sig_src=25 --y_src=90 --src_gain=1.4" ;;
  *) echo "unknown TAG='$TAG' (s0_baseline|s1_thin|s2_thinstiff|s3_narrow|s4_gain)"; exit 1 ;;
esac

OUTDIR="$PBS_O_WORKDIR/output/sweep/$TAG"
mkdir -p "$OUTDIR"
echo "TAG=$TAG  DAYS=$DAYS  SRC='$SRC'  OUTDIR=$OUTDIR"

# Fresh short pump run for this config (no checkpoint -> starts from rest and spins up).
peak_memusage $JULIA --project "$SCRIPT" \
    --simname="$TAG" --tide=0 --pump=1 $SRC --arch=gpu --outdir="$OUTDIR" \
    --stop_days="$DAYS" --wall_time_limit=11.5 \
    2>&1 | tee "logs/sweep_${TAG}.out"
